consumer_key: "1JNJlIgHGgQF213iVzmgB7LSl"
consumer_secret: "pH3cEv9nQFv4r9rS3OhV6PcuaQhO8cZyv5WpyNfFd2Rlxrpr6p"
access_key: "1469761271709028359-Ac9jwcGkZmaXFC7yLgzlHGkM6ProjC"
access_secret: "hXW5SqHGVpOogxnnKDrXJdDdC5Nk1lnMFiyiu6hRJUx88"
bearer_token: "AAAAAAAAAAAAAAAAAAAAAGPIWwEAAAAA6L7Pk7nWV0i7G%2FS7W2pIdnEOEUc%3DqicKzjYrHwqHHHsT35CHcY0wvTCWuNkPyOZ3PEQy8iacruf9a9"

twitter_users:
  - nickbschroer
  - bobondermo
  - @meaccoleman

num_epochs: 5
gen_epochs: 1
batch_size: 128
train_size: 1.0
new_model: False

# Only applicable if new_model: True
model_config:
  rnn_layers: 2
  rnn_size: 128
  rnn_bidirectional: False
  max_length: 40
  dim_embeddings: 100
  word_level: False
